name: docker-consumption-app

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: consumption-app
    container_name: docker-container-consumption-app
    ports: 
      - "8000:8000"
    volumes:
      - .:/app

  db:
    image: postgres:16
    container_name: postgres-db
    restart: always
    environment:
     POSTGRES_USER: my_user
     POSTGRES_PASSWORD: my_password
     POSTGRES_DB: my_database
    ports:  
     - "5432:5432"
      


      


